name: supertypes
description: A library for better, super records
version: 0.0.5
repository: https://github.com/exaby73/supertypes/tree/master/packages/supertypes

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  barrel_files_annotation: ^0.1.1

dev_dependencies:
  barrel_files: ^0.1.1
  build_runner: ^2.4.6
  lint: ^2.2.0
  test: ^1.24.0
