name: example
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.2.0

# Add regular dependencies here.
dependencies:
  supertypes: ^0.0.1

dev_dependencies:
  build_runner: ^2.4.6
  lint: ^2.2.0
  supertypes_generator:
    path: ..
  test: ^1.24.0
