name: supertypes_generator
description: Generator for supertypes
version: 0.0.5
repository: https://github.com/exaby73/supertypes/tree/master/packages/supertypes_generator

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  analyzer: ^6.3.0
  build: ^2.4.1
  source_gen: ^1.4.0
  supertypes: ^0.0.5

dev_dependencies:
  lint: ^2.2.0
  test: ^1.24.0
